import _about1 from './img/about/grupo_de_amigos_B.png';
import _about1_2x from './img/about/grupo_de_amigos_B@2x.png';
import _about3 from './img/about/mi_avatar.png';
import _about3_3x from './img/about/mi_avatar@2x.png';
import _about2 from './img/about/redondo_linea_ambas.png';
import _about2_2x from './img/about/redondo_linea_ambas@2x.png';
import _comic3 from './img/comic/comic10.jpg';
import _comic4 from './img/comic/comic11.jpg';
import _comic5 from './img/comic/comic12.jpg';
import _comic6 from './img/comic/comic13.jpg';
import _comic7 from './img/comic/comic14.jpg';
import _comic8 from './img/comic/comic15.jpg';
import _comic9 from './img/comic/comic16.jpg';
import _comic10 from './img/comic/comic17.jpg';
import _comic11 from './img/comic/comic18.jpg';
import _comic1 from './img/comic/comic7.jpg';
import _comic2 from './img/comic/comic9.jpg';
import _contraportada from './img/comic/contraportada.jpg';
import _portada from './img/comic/portada.jpg';
import _microLogo from './img/favicon/Recurso15.png';
import _smallLogo from './img/favicon/Recurso16.png';
import _mediumLogo from './img/favicon/Recurso17.png';
import _bigLogo from './img/favicon/Recurso18.png';
import _background from './img/general/general_background.jpg';
import _upArrow from './img/icons/arrow/Recurso6.png';
import _downArrow from './img/icons/arrow/Recurso7.png';
import _rightArrow from './img/icons/arrow/Recurso8.png';
import _leftArrow from './img/icons/arrow/Recurso9.png';
import _rigthMenuArrow from './img/icons/arrow/Trazado1.png';
import _microFacebook from './img/icons/social/facebook2.png';
import _smallFacebook from './img/icons/social/facebook3.png';
import _mediumFacebook from './img/icons/social/facebook4.png';
import _bigFacebook from './img/icons/social/facebook5.png';
import _microInstagram from './img/icons/social/instagram-logo.png';
import _smallInstagram from './img/icons/social/instagram-logo1.png';
import _mediumInstagram from './img/icons/social/instagram-logo2.png';
import _bigInstagram from './img/icons/social/instagram-logo3.png';
import _arte_final_estacion from './img/modelsheet/arte-final-estacion.png';
import _concept_art_station from './img/modelsheet/concept-art-estacion.png';
import _cruce_de_coches from './img/modelsheet/cruce-de-coches.png';
import _marta_acting from './img/modelsheet/marta-acting-modelsheet.jpg';
import _marta_expresion from './img/modelsheet/marta-expression-modelsheet.jpg';
import _monica_acting from './img/modelsheet/monica-acting-modelsheet.jpg';
import _monica_expresion from './img/modelsheet/monica-expression-modelsheet.jpg';

export const bigLogo = _bigLogo;
export const microLogo = _microLogo;
export const smallLogo = _smallLogo;
export const mediumLogo = _mediumLogo;
export const microFacebook = _microFacebook;
export const smallFacebook = _smallFacebook;
export const mediumFacebook = _mediumFacebook;
export const bigFacebook = _bigFacebook;
export const microInstagram = _microInstagram;
export const smallInstagram = _smallInstagram;
export const mediumInstagram = _mediumInstagram;
export const bigInstagram = _bigInstagram;
export const upArrow = _upArrow;
export const downArrow = _downArrow;
export const rightArrow = _rightArrow;
export const leftArrow = _leftArrow;
export const rigthMenuArrow = _rigthMenuArrow;
export const portada = _portada;
export const contraportada = _contraportada;
export const comic1 = _comic1;
export const comic2 = _comic2;
export const comic3 = _comic3;
export const comic4 = _comic4;
export const comic5 = _comic5;
export const comic6 = _comic6;
export const comic7 = _comic7;
export const comic8 = _comic8;
export const comic9 = _comic9;
export const comic10 = _comic10;
export const comic11 = _comic11;
export const about1 = _about1;
export const about1_2x = _about1_2x;
export const about2 = _about2;
export const about2_2x = _about2_2x;
export const about3 = _about3;
export const about3_3x = _about3_3x;
export const background = _background;
export const monica_acting = _monica_acting;
export const monica_expresion = _monica_expresion;
export const marta_acting = _marta_acting;
export const marta_expresion = _marta_expresion;
export const concept_art_station = _concept_art_station
export const cruce_de_coches = _cruce_de_coches
export const arte_final_estacion = _arte_final_estacion
